import socket
import threading
import time


# Define the server parameters
HOST = "0.0.0.0"  # Listen on all available interfaces
PORT = 23  # Use Telnet default port

# List to store connected clients
clients = []



def get_user_input(client_socket):
    input_buffer = ""
    while True:
        data = client_socket.recv(1).decode('utf-8')
        if not data or data == "\n":
            break
        input_buffer += data
    return input_buffer.strip()

def handle_client(client_socket):
    welcome_message = (
        "\n\r\t\t\t                           ||     || |||||||| ||       ||||||||| ||||||||| |||||||||| ||||||||"
        "\n\r\t\t\t                           ||     || |        ||       ||        |       | || |||| || |       "
        "\n\r\t\t\t                           ||     || |        ||       ||        |       | ||  ||  || |       "
        "\n\r\t\t\t                           ||     || |||||||| ||       ||        |       | ||      || ||||||||"
        "\n\r\t\t\t                           || ||| || |        ||       ||        |       | ||      || |       "
        "\n\r\t\t\t                           ||||||||| |        ||       ||        |       | ||      || |       "
        "\n\r\t\t\t                           ||||||||| |||||||| |||||||| ||||||||| ||||||||| ||      || ||||||||"
        "\n\r                                                                                                      "
        "\n\r\t\t\t                                             ||||||||||||||| |||||||||           "
        "\n\r\t\t\t                                                  |||||      |       |           "
        "\n\r\t\t\t                                                  |||||      |       |           "
        "\n\r\t\t\t                                                  |||||      |       |           "
        "\n\r\t\t\t                                                  |||||      |       |           "
        "\n\r\t\t\t                                                  |||||      |       |           "
        "\n\r\t\t\t                                                  |||||      |||||||||           "
        "\n\r                                                                                                      "
        "\n\r\t\t\t    ||     || |||||||| ||||||||||  |||||||||                   |||       ||          ||||||||| ||       || ||||||||"
        "\n\r\t\t\t    ||     || |      | || |||| ||  ||                         || ||      ||          |       | || |     || |       "
        "\n\r\t\t\t    ||     || |      | ||  ||  ||  ||                        ||   ||     ||          |       | ||  |    || |       "
        "\n\r\t\t\t    ||||||||| |      | ||      ||  |||||||||   ||||||||     |||||||||    ||          |       | ||   |   || ||||||||"
        "\n\r\t\t\t    ||     || |      | ||      ||  ||                      ||       ||   ||          |       | ||    |  || |       "
        "\n\r\t\t\t    ||     || |      | ||      ||  ||                     ||         ||  ||          |       | ||     | || |       "
        "\n\r\t\t\t    ||     || |||||||| ||      ||  |||||||||             ||           || ||||||||||| ||||||||| ||       || ||||||||"
        "\n\r\t\t\t                                                                                                      "
    )
    client_socket.send("\n\rQuick Reminder! Play this game in full screen to enjoy!".encode('utf-8'))
    time.sleep(5)
    client_socket.send(welcome_message.encode('utf-8'))
    time.sleep(5)
    client_socket.send("\n\rWelcome! Home-Alone is a text-based adventure game! Players has to control our main protagonist, Zach, around the house!".encode('utf-8'))
    time.sleep(4)
    client_socket.send("\n\rControl Zach using simple command like (a or b or c)" .encode('utf-8'))
    time.sleep(4)
    client_socket.send("\n\rYour journey starts here!".encode('utf-8'))
    time.sleep(3)
    client_socket.send("\n\r2023, Midnight".encode('utf-8'))
    time.sleep(3)
    client_socket.send("\n\rYou wake up from your sleep.".encode('utf-8'))
    time.sleep(5)
    client_socket.send("\n\rWhy?".encode('utf-8'))
    time.sleep(2)
    client_socket.send("\n\rBecause you heard something coming out from your parent's room".encode('utf-8'))
    time.sleep(5)
    client_socket.send("\n\rBut you remembered your parents are working...".encode('utf-8'))
    time.sleep(4)
    client_socket.send("\n\rYou choose to-".encode('utf-8'))
    time.sleep(2)
    client_socket.send("\n\r(a - Go To Living Room/b - Go To Parent's Room/c - Search your room)".encode('utf-8'))
    choose1a = get_user_input(client_socket)
    if choose1a.strip().lower() == "a":
        client_socket.send("\n\rYou go to the living room".encode('utf-8'))
        time.sleep(3)
        client_socket.send("\n\rYou remembered your parents keep a spare key around here somewhere...".encode('utf-8'))
        time.sleep(3)
        client_socket.send("\n\rYou -".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\r(a - Search the drawer/b - Search the table)".encode('utf-8'))
        time.sleep(3)
        choose2a = get_user_input(client_socket)
        if choose2a.strip().lower() == "a":
            client_socket.send("\n\rYou search the drawer...".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou find an old picture of you and your parents,".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\ra note,".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rand an old Nokia-3310...".encode('utf-8'))
            time.sleep(3)
            client_socket.send("\n\rFor unknown reason, you decided to keep it. Just in case.".encode('utf-8'))
            time.sleep(3)
            client_socket.send("\n\rYou read the note.".encode('utf-8'))
            time.sleep(3)
            client_socket.send("\n\r|Dear Zach, If you are seeing this you might be looking the key to our bedroom! Be sure not to watch the TV until late!".encode('utf-8'))
            time.sleep(4)
            client_socket.send("\n\rI hid the key in the cabinet, don't foget it! Love you - Mom|".encode('utf-8'))
            time.sleep(3)
            client_socket.send("\n\rYou keep the note in your pocket and head to the cabinet".encode('utf-8'))
            time.sleep(3)
            client_socket.send("\n\rYou find a box and some coins.".encode('utf-8'))
            time.sleep(3)
            client_socket.send("\n\rBut the box was locked by a passcode...".encode('utf-8'))
            time.sleep(3)
            client_socket.send("\n\rThe password to it is easy! Just type Key - Mom".encode('utf-8'))
            time.sleep(3)
            client_socket.send("\n\rYou insert-".encode('utf-8'))
            choose3a = get_user_input(client_socket)
            if choose3a.strip().lower() == "key" or "Key":
                client_socket.send("\n\rThe box opens!".encode('utf-8'))
                time.sleep(3)
                client_socket.send("\n\r...".encode('utf-8'))
                time.sleep(3)
                client_socket.send("\n\rUh Oh.".encode('utf-8'))
                time.sleep(2)
                client_socket.send("\n\rYou open up a PANDORA'S BOX!!".encode('utf-8'))
                time.sleep(2)
                client_socket.send("\n\rYou- ".encode('utf-8'))
                time.sleep(2)
                client_socket.send("\n\r(a - Close the Box/b - Let the box open)".encode('utf-8'))
                choose4a = get_user_input(client_socket)
                if choose4a.strip().lower() == "a":
                        client_socket.send("\n\rThank god you close the box in time...".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rWho knows what happens when you let the box open...".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rAnyway, A key suddenly appeared on your inventory!".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rYou headed to your parent's room immediately".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rYou insert the key into the door.".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rThe door opens!".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\r...".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rYou see a mysterious figure standing at the window...".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rThe figure meows at you as it hop away...".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rYou realised it was a cat all along.".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rThe cat scratched the curtains and the bed sheets...".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rAfter you close the window, you head to sleep.".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rBut you are one hundred percent sure someone was here before...".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rMaybe you find other routes?".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\r---Neutral Ending---".encode('utf-8'))
                elif choose4a.strip().lower() == "b":
                        client_socket.send("\n\rOh no! The box is sucking you in!".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rIt is also spawning many unknown creatures!".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rThe world is going to be ruined thanks to you...".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\r---Bad Ending---".encode('utf-8'))
            else:
                client_socket.send("\n\rYou type the wrong passcode.".encode('utf-8'))
                time.sleep(2)
                client_socket.send("\n\rThe box explodes.".encode('utf-8'))
                time.sleep(2)
                client_socket.send("\n\r---Bad Ending---".encode('utf-8'))
        if choose2a.strip().lower() == "b":
            client_socket.send("\n\rYou search the table.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou find a phone, some cigarette, some random pills, and a bottle of vodka.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou take the phone for safety.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou leave a disgusted face towards the cigarettes and the vodka. >:( (Remember! Smoking and Drinking is bad XX))".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou-".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\r(a - Call your parent)".encode('utf-8'))
            choose3cc = get_user_input(client_socket)
            if choose3cc.strip().lower() == "a":
                    client_socket.send("\n\r-Ring-".encode('utf-8'))
                    time.sleep(1)
                    client_socket.send("\n\r-Ring-".encode('utf-8'))
                    time.sleep(1)
                    client_socket.send("\n\r-Ring-".encode('utf-8'))
                    time.sleep(1)
                    client_socket.send("\n\r???:Hello. This is Pearl. Who is speaking?".encode('utf-8'))
                    time.sleep(2)
                    client_socket.send("\n\rZach: Mom? Is that you?".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rMom: Zach?! Why are you calling? I thought you were sleeping?!".encode('utf-8')) 
                    time.sleep(3)
                    client_socket.send("\n\rZach: I heard something coming out from your room. What should I do?".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rMom: Hold in there, I will try to call the police. Stay safe.".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rZach: Is there someone inside our house?".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rMom: Let's not hope that. I'll try to get back as soon as I could.".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rZach: OK.".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rYou decide to hide under the couch.".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rYou heard the door opens...".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rIt could be someone...".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rcoming downstairs..".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rYou-".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\r(a - Run Outside the House/b - Hide)".encode('utf-8'))
                    choose4bb = get_user_input(client_socket)
                    if choose4bb.strip().lower() == "a":
                        client_socket.send("\n\rYou decide to run outside your house".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rWhen the police came, the myterious object was not yet to be found...".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rDuring investigating, it was sure that someone has been searching for something...".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rMaybe If you waited? Imagine you can catch the myterious figure and hand it to justice...".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\r---Neutral Ending---".encode('utf-8'))
                    elif choose4bb.strip().lower() == "b":
                        client_socket.send("\n\rYou hide under the sofa.".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rYou see the man's leg.".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rYou continue to hde.".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rThe man keeps on searching for something...".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rCould it be?".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rCould the man be looking for a box?".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rPerhaps something assembles a Pandora's Box?".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rYou-".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\r-(a - Open the Pandora's Box/b - Do nothing)".encode('utf-8'))
                        choose5aa = get_user_input(client_socket)
                        if choose5aa.strip().lower() == "a":
                               client_socket.send("\n\rYou open the Pandora's Box.".encode('utf-8'))
                               time.sleep(3)
                               client_socket.send("\n\rThe man is sucked by the Pandora's Box!".encode('utf-8'))
                               time.sleep(3)
                               client_socket.send("\n\rWhen the man got sucked in, and the Pandora's Box turn to normal.".encode('utf-8'))
                               time.sleep(3)
                               client_socket.send("\n\rThe police arrives. Along with your parent.".encode('utf-8'))
                               time.sleep(3)
                               client_socket.send("\n\rYou told them what happened and they release the man out of the Pandora's Box.".encode('utf-8'))
                               time.sleep(3)
                               client_socket.send("\n\rSeems like some mystery are better left unsolved...".encode('utf-8'))
                               time.sleep(3)
                               client_socket.send("\n\r---Good Ending---".encode('utf-8'))
                        if choose5aa.strip().lower() == "b":
                               client_socket.send("\n\rThe mysterious man find you hiding under the couch.".encode('utf-8'))
                               time.sleep(3)
                               client_socket.send("\n\rYou get knock out by the mysterious man...".encode('utf-8'))
                               time.sleep(3)
                               client_socket.send("\n\r---Bad Ending---".encode('utf-8'))
    if choose1a.strip().lower() == "b":
        client_socket.send("\n\rYou headed to your parent's room.".encode('utf-8'))
        time.sleep(3)
        client_socket.send("\n\rYou do realised it was locked right?".encode('utf-8'))
        time.sleep(3)
        client_socket.send("\n\rFor some reason you feel dumb and thinking about what is life right now.".encode('utf-8'))
        time.sleep(3)
        client_socket.send("\n\rYou- ".encode('utf-8'))
        time.sleep(3)
        client_socket.send("\n\r(a - Go To Living Room/b - Search your room)".encode('utf-8'))
        choose2b = get_user_input(client_socket)
        if choose2b.strip().lower() == "a":
                    client_socket.send("\n\rYou go to the living room".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rYou remembered your parents keep a spare key around here somewhere...".encode('utf-8'))
                    time.sleep(3)
                    client_socket.send("\n\rYou -".encode('utf-8'))
                    time.sleep(2)
                    client_socket.send("\n\r(a - Search the drawer/b - Search the table)".encode('utf-8'))
                    time.sleep(3)
                    choose2c = get_user_input(client_socket)
                    if choose2c.strip().lower() == "a":
                        client_socket.send("\n\rYou search the drawer...".encode('utf-8'))  
                        time.sleep(2)
                        client_socket.send("\n\rYou find an old picture of you and your parents,".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\ra note,".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rand an old Nokia-3310...".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rFor unknown reason, you decided to keep it. Just in case.".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rYou read the note.".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\r|Dear Zach, If you are seeing this you might be looking the key to our bedroom! Be sure not to watch the TV until late!".encode('utf-8'))
                        time.sleep(4)
                        client_socket.send("\n\rI hid the key in the cabinet, don't foget it! Love you - Mom|".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rYou keep the note in your pocket and head to the cabinet".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rYou find a box and some coins.".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rBut the box was locked by a passcode...".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rThe password to it is easy! Just type Key - Mom".encode('utf-8'))
                        time.sleep(3)
                        client_socket.send("\n\rYou insert-".encode('utf-8'))
                        choose3b = get_user_input(client_socket)
                        if choose3b.strip().lower() == "key" or "Key":
                            client_socket.send("\n\rThe box opens!".encode('utf-8'))
                            time.sleep(3)
                            client_socket.send("\n\r...".encode('utf-8'))
                            time.sleep(3)
                            client_socket.send("\n\rUh Oh.".encode('utf-8'))
                            time.sleep(2)
                            client_socket.send("\n\rYou open up a PANDORA'S BOX!!".encode('utf-8'))
                            time.sleep(2)
                            client_socket.send("\n\rYou- ".encode('utf-8'))
                            time.sleep(2)
                            client_socket.send("\n\r(a - Close the Box/b - Let the box open)".encode('utf-8'))
                            choose4b = get_user_input(client_socket)
                            if choose4b.strip().lower() == "a":
                                client_socket.send("\n\rThank god you close the bo2bx in time...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rWho knows what happens when you let the box open...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rAnyway, A key suddenly appeared on your inventory!".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rYou headed to your parent's room immediately".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rYou insert the key into the door.".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rThe door opens!".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\r...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rYou see a mysterious figure standing at the window...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rThe figure meows at you as it hop away...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rYou realised it was a cat all along.".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rThe cat scratched the curtains and the bed sheets...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rAfter you close the window, you head to sleep.".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rBut you are one hundred percent sure someone was here before...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rMaybe you find other routes?".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\r---Neutral Ending---".encode('utf-8'))
                            elif choose4b.strip().lower() == "b":
                                client_socket.send("\n\rOh no! The box is sucking you in!".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rIt is also spawning many unknown creatures!".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rThe world is going to be ruined thanks to you...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\r---Bad Ending---".encode('utf-8'))
                        else:
                            client_socket.send("\n\rYou type the wrong passcode.".encode('utf-8'))
                            time.sleep(2)
                            client_socket.send("\n\rThe box explodes.".encode('utf-8'))
                            time.sleep(2)
                            client_socket.send("\n\r---Bad Ending---".encode('utf-8'))
                    if choose2c.strip().lower() == "b":
                        client_socket.send("\n\rYou search the table.".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rYou find a phone, some cigarette, some random pills, and a bottle of vodka.".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rYou take the phone for safety.".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rYou leave a disgusted face towards the cigarettes and the vodka. >:( (Remember! Smoking and Drinking is bad XX))".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\rYou-".encode('utf-8'))
                        time.sleep(2)
                        client_socket.send("\n\r(a - Call your parent)".encode('utf-8'))
                        choose3ccc = get_user_input(client_socket)
                        if choose3ccc.strip().lower() == "a":
                                client_socket.send("\n\r-Ring-".encode('utf-8'))
                                time.sleep(1)
                                client_socket.send("\n\r-Ring-".encode('utf-8'))
                                time.sleep(1)
                                client_socket.send("\n\r-Ring-".encode('utf-8'))
                                time.sleep(1)
                                client_socket.send("\n\r???:Hello. This is Pearl. Who is speaking?".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rZach: Mom? Is that you?".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rMom: Zach?! Why are you calling? I thought you were sleeping?!".encode('utf-8')) 
                                time.sleep(2)
                                client_socket.send("\n\rZach: I heard something coming out from your room. What should I do?".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rZach: Is there someone inside our house?".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rMom: Let's not hope that. I'll try to get back as soon as I could.".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rZach: OK.".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rYou decide to hide under the couch.".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rYou heard the door opens...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rIt could be someone...".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rcoming downstairs..".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\rYou-".encode('utf-8'))
                                time.sleep(2)
                                client_socket.send("\n\r(a - Run Outside the House/b - Hide)".encode('utf-8'))
                                choose4bbb = get_user_input(client_socket)
                                if choose4bbb.strip().lower() == "a":
                                    client_socket.send("\n\rYou decide to run outside your house".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rWhen the police came, the myterious object was not yet to be found...".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rDuring investigating, it was sure that someone has been searching for something...".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rMaybe If you waited? Imagine you can catch the myterious figure and hand it to justice...".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\r---Neutral Ending---".encode('utf-8'))
                                elif choose4bbb.strip().lower() == "b":
                                    client_socket.send("\n\rYou hide under the sofa.".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rYou see the man's leg.".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rYou continue to hde.".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rThe man keeps on searching for something...".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rCould it be?".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rCould the man be looking for a box?".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rPerhaps something assembles a Pandora's Box?".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\rYou-".encode('utf-8'))
                                    time.sleep(2)
                                    client_socket.send("\n\r-(a - Open the Pandora's Box/b - Do nothing)".encode('utf-8'))
                                    choose5aaa = get_user_input(client_socket)
                                    if choose5aaa.strip().lower() == "a":
                                        client_socket.send("\n\rYou open the Pandora's Box.".encode('utf-8'))
                                        time.sleep(2)
                                        client_socket.send("\n\rThe man is sucked by the Pandora's Box!".encode('utf-8'))
                                        time.sleep(2)
                                        client_socket.send("\n\rWhen the man got sucked in, and the Pandora's Box turn to normal.".encode('utf-8'))
                                        time.sleep(2)
                                        client_socket.send("\n\rThe police arrives. Along with your parent.".encode('utf-8'))
                                        time.sleep(2)
                                        client_socket.send("\n\rYou told them what happened and they release the man out of the Pandora's Box.".encode('utf-8'))
                                        time.sleep(2)
                                        client_socket.send("\n\rSeems like some mystery are better left unsolved...".encode('utf-8'))
                                        time.sleep(2)
                                        client_socket.send("\n\r---Good Ending---".encode('utf-8'))
                                    if choose5aaa.strip().lower() == "b":
                                        client_socket.send("\n\rThe mysterious man find you hiding under the couch.".encode('utf-8'))
                                        time.sleep(2)
                                        client_socket.send("\n\rYou get knock out by the mysterious man...".encode('utf-8'))
                                        time.sleep(2)
                                        client_socket.send("\n\r---Bad Ending---".encode('utf-8'))
        if choose2b.strip().lower() == "b":
            client_socket.send("\n\rYou remember you kept a replica of your parent's key before.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou used to use this key to open your parent's room to watch cartoons when they were away.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou forgot where you hide it...".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rReally?".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou- ".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou are searching ||The Moutain of DOOM||".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rWhy?".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rThis is where you put all your stuffs here!".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rIt is a pile of random items.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\r*Rubble* *Rubble*".encode('utf-8'))
            time.sleep(1)
            client_socket.send("\n\r*Rubble* *Rubble*".encode('utf-8'))
            time.sleep(1)
            client_socket.send("\n\rAfter searching, you only find your old PSP".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou search under your bed.?".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou found the backup key!".encode('utf-8'))
            time.sleep(1)
            client_socket.send("\n\rYou headed to your parent's room immediately".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou insert the key into the door.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rThe door opens!".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\r...".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou see a mysterious figure standing at the window...".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rThe figure meows at you as it hop away...".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rYou realised it was a cat all along.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rThe cat scratched the curtains and the bed sheets...".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rAfter you close the window, you head to sleep.".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rBut you are one hundred percent sure someone was here before...".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\rMaybe you find other routes?".encode('utf-8'))
            time.sleep(2)
            client_socket.send("\n\r---Neutral Ending---".encode('utf-8'))
    if choose1a.strip().lower() == "c":
        client_socket.send("\n\rYou remember you kept a replica of your parent's key before.".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rYou used to use this key to open your parent's room to watch cartoons when they were away.".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rYou forgot where you hide it...".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rReally?".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rYou are searching ||The Moutain of DOOM||".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rWhy?".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rThis is where you put all your stuffs here!".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rIt is a pile of random items.".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\r*Rubble* *Rubble*".encode('utf-8'))
        time.sleep(1)
        client_socket.send("\n\r*Rubble* *Rubble*".encode('utf-8'))
        time.sleep(1)
        client_socket.send("\n\rAfter searching, you only find your old PSP".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rYou search under your bed.".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rYou found the backup key!".encode('utf-8'))
        time.sleep(1)
        client_socket.send("\n\rYou headed to your parent's room immediately".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rYou insert the key into the door.".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rThe door opens!".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\r...".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rYou see a mysterious figure standing at the window...".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rThe figure meows at you as it hop away...".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rYou realised it was a cat all along.".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rThe cat scratched the curtains and the bed sheets...".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rAfter you close the window, you head to sleep.".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rBut you are one hundred percent sure someone was here before...".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\rMaybe you find other routes?".encode('utf-8'))
        time.sleep(2)
        client_socket.send("\n\r---Neutral Ending---".encode('utf-8'))
    



    try:
        clients.remove(client_socket)
    except ValueError:
        pass  # Client already removed
    
    client_socket.close()

def main():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.bind((HOST, PORT))
    server.listen(5)
    print(f"Telnet Server listening on {HOST}:{PORT}")
    
    while True:
        client_socket, client_addr = server.accept()
        print(f"Accepted connection from {client_addr}")
        
        clients.append(client_socket)
        
        client_thread = threading.Thread(target=handle_client, args=(client_socket,))
        client_thread.start()

if __name__ == "__main__":
    main()
